CREATE TABLE departmenttts (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(50) UNIQUE
);
CREATE TABLE incomess (
    income_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id NUMBER,
    year NUMBER,
    income NUMBER,
    CONSTRAINT fkk_department FOREIGN KEY (department_id) REFERENCES departmenttts(department_id)
);

INSERT INTO departmenttts (department_name) VALUES ('Administration');
INSERT INTO departmenttts (department_name) VALUES ('Marketing');
INSERT INTO departmenttts (department_name) VALUES ('Purchasing');
INSERT INTO departmenttts (department_name) VALUES ('Human Resources');
INSERT INTO departmenttts (department_name) VALUES ('Shipping');
INSERT INTO departmenttts (department_name) VALUES ('IT');
INSERT INTO departmenttts (department_name) VALUES ('Public Relations');
INSERT INTO departmenttts (department_name) VALUES ('Sales');
INSERT INTO departmenttts (department_name) VALUES ('Executive');
INSERT INTO departmenttts (department_name) VALUES ('Finance');
INSERT INTO departmenttts (department_name) VALUES ('Accounting');


DECLARE
    v_start_year NUMBER := 2001;
    v_end_year NUMBER := 2023;
BEGIN
    FOR dept_row IN (SELECT * FROM departmenttts) LOOP
        FOR i IN v_start_year..v_end_year LOOP
            INSERT INTO incomess (department_id, year, income)
            VALUES (
                dept_row.department_id,
                i,
                ROUND(DBMS_RANDOM.VALUE(10000, 50000) * i * DBMS_RANDOM.VALUE(0.8, 1.2), 2)
            );
        END LOOP;
    END LOOP;
END;
/

SELECT i.year AS "Year", 
    d.department_name AS "Department", 
    ROUND(i.income) AS "Income"
    FROM incomess i
LEFT JOIN departmenttts d 
ON i.department_id = d.department_id;

